/**
 * Run dashboard — a static HTML viewer written into the artifact dir.
 *
 * The X-post caption is a `*.preview.getsolari.com` URL when the plan allows
 * serving it from a sandbox; on Free (one concurrent sandbox, already spent
 * on reconciliation) the dashboard is the local `artifacts/<runId>/dashboard.html`.
 * Either way it is the same file: steps, stream URL, replay link, cost.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { EvalReport, JournalEvent } from "./types.ts";

/** Render the dashboard HTML for a finished (or in-progress) run. */
export function renderDashboard(report: EvalReport, events: JournalEvent[]): string {
  const rows = report.predicates
    .map((p) => `<tr><td>${p.ok ? "✅" : "❌"}</td><td>${esc(p.name)}</td><td>${esc(p.detail ?? "")}</td></tr>`)
    .join("\n");
  const steps = events
    .filter((e) => e.type === "step.start")
    .map((e) => {
      const id = (e as { id: string }).id;
      const ok = events.find((x) => x.type === "step.ok" && (x as { id: string }).id === id);
      const fail = events.find((x) => x.type === "step.fail" && (x as { id: string }).id === id);
      const state = fail ? "❌" : ok ? "✅" : "…";
      const ms = ok ? `${(ok as { ms: number }).ms}ms` : "";
      return `<tr><td>${state}</td><td>${esc(id)}</td><td>${esc((e as { surface: string }).surface)}</td><td>${ms}</td></tr>`;
    })
    .join("\n");
  const link = (url: string | null, label: string) =>
    url ? `<a href="${esc(url)}">${label}</a>` : `<span class="dim">${label}: n/a</span>`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>noapi run ${esc(report.runId)}</title>
<style>
body{font:14px/1.5 ui-monospace,monospace;background:#0d1117;color:#c9d1d9;max-width:840px;margin:2rem auto;padding:0 1rem}
h1{font-size:1.2rem}a{color:#58a6ff}table{border-collapse:collapse;width:100%;margin:1rem 0}
td,th{border:1px solid #30363d;padding:.3rem .6rem;text-align:left}
.badge{display:inline-block;padding:.2rem .7rem;border-radius:1rem;background:${report.ok ? "#1a7f37" : "#b62324"};color:#fff}
.dim{color:#8b949e}.banner{background:#161b22;border:1px solid #30363d;padding:.6rem 1rem;border-radius:.5rem}
</style></head><body>
<div class="banner"><strong>NOAPI</strong> — run ${esc(report.runId)} <span class="badge">${report.ok ? "ok" : "failed"}</span></div>
<h1>${esc(report.scenario)}</h1>
<p>wall ${(report.wallMs / 1000).toFixed(1)}s · cost ~$${report.costUsdEstimate.toFixed(4)} · rewinds ${report.rewinds} ·
browser ${report.surfaces.browserSec}s · sandbox ${report.surfaces.sandboxSec}s · desktop ${report.surfaces.desktopSec}s</p>
<p>${link(report.streamUrl, "desktop stream (vnc)")} · ${link(report.desktopRecordingUrl, "desktop recording (mp4)")} · ${link(report.replayUrl, "browser replay (rrweb)")} · ${link(report.previewUrl, "dashboard preview")}</p>
<h2>steps</h2><table><tr><th></th><th>step</th><th>surface</th><th>ms</th></tr>${steps}</table>
<h2>eval predicates</h2><table><tr><th></th><th>predicate</th><th>detail</th></tr>${rows}</table>
<p class="dim">artifacts: journal.ndjson · eval.json · MANIFEST.sha256 — generated by noapi</p>
</body></html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Write the dashboard into the artifact dir; returns the file path. */
export function writeDashboard(dir: string, report: EvalReport, events: JournalEvent[]): string {
  const path = join(dir, "dashboard.html");
  writeFileSync(path, renderDashboard(report, events));
  return path;
}
